name: Release

on:
  push:
    tags:
      - "v-release*.*" # Adjust the tag pattern as needed

permissions:
  contents: read # for checkout

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm clean-install

      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures

      - name: Fetch all tags
        run: git fetch --tags

      - name: Extract Tag Name
        id: extract_tag
        run: |
          TAG_NAME=${GITHUB_REF/refs\/tags\//}
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Create and switch to release branch
        run: |
          git fetch origin
          if git rev-parse --verify origin/release-branch; then
            git checkout release-branch
            git pull origin release-branch
          else
            git checkout -b release-branch
            git push --set-upstream origin release-branch
          fi

      - name: Configure Git to handle divergent branches
        run: |
          git config pull.rebase false  # Using merge strategy, you can change to true for rebase or 'ff only' for fast-forward only

      - name: Pull latest changes from master and merge
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin master --allow-unrelated-histories --strategy-option theirs  # or use --strategy-option ours

      - name: Check if tag already exists
        id: check_tag
        run: |
          TAG_NAME=${{ env.TAG_NAME }}
          if git rev-parse "refs/tags/$TAG_NAME" >/dev/null 2>&1; then
            echo "Tag $TAG_NAME already exists"
            echo "::set-output name=tag_exists::true"
          else
            echo "::set-output name=tag_exists::false"
          fi

      - name: Run Semantic Release
        if: steps.check_tag.outputs.tag_exists == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ env.TAG_NAME }}
        run: |
          echo "Running Semantic Release with tag $TAG_NAME"
          npx semantic-release --tag $TAG_NAME --no-ci

      - name: Add and commit changes
        if: steps.check_tag.outputs.tag_exists == 'false'
        run: |
          git add .
          git commit -m "chore(release): update release notes [skip ci]"

      - name: Push changes to release branch
        if: steps.check_tag.outputs.tag_exists == 'false'
        run: |
          git push origin release-branch

      - name: Create Pull Request for Release
        if: steps.check_tag.outputs.tag_exists == 'false'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(release): ${nextRelease.version} [skip ci]"
          branch: release-branch
          title: "Release ${nextRelease.version}"
          body: "This pull request includes the release of version ${nextRelease.version}."
          base:
