name: Release

on:
  push:
    tags:
      - "v-release*.*" # Adjust the tag pattern as needed

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.13.1"

      - name: Install dependencies
        run: npm install

      - name: Create and switch to release branch
        run: |
          git checkout -b release-branch

      - name: Pull latest changes from master and merge
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin master --allow-unrelated-histories --strategy-option theirs  # or use --strategy-option ours

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      - name: Push changes to release branch
        run: |
          git push --set-upstream origin release-branch

      - name: Create Pull Request for Release
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(release): ${nextRelease.version} [skip ci]"
          branch: release-branch
          title: "Release ${nextRelease.version}"
          body: "This pull request includes the release of version ${nextRelease.version}."
          base: master
